### ISSUE TITLE
Support servers having different WEB_DOMAIN and LOCAL_DOMAIN

### ISSUE THREAD

**Issue by rgrunbla** [nolanlawson/pinafore#2245] opened 2022-11-25 07:55 UTC
Hello,

Mastodon servers can be configured to have different LOCAL_DOMAIN (the address of the server) and WEB_DOMAIN (the address of the web interface), per https://docs.joinmastodon.org/admin/config/#basic

Currently, Pinafore does not support this, and asks for the web domain, without explaining the difference. Supporting this would mean, that, for example, people can input "sciences.re" (which my instance LOCAL_DOMAIN) on https://pinafore.social/settings/instances/add and have it work as expected, instead of inputting "social.sciences.re", which is only the address of the web interface, but not the address of the server.

One example of this being handled in python is https://github.com/ProgVal/Limnoria/blob/master/plugins/Fediverse/activitypub.py#L120-L185

Thanks !

**Comment by nolanlawson** [comment] 2022-11-25 15:47
Thanks for reporting this issue! Looks like a duplicate of https://github.com/nolanlawson/pinafore/issues/2169

Closing for now. Thanks!

**Closed by nolanlawson** 2022-11-25 15:47 UTC
