### ISSUE TITLE
The mention dialog on user profiles does not appear unless I refresh the page first

### ISSUE THREAD

**Issue by Hund** [nolanlawson/pinafore#1165] opened 2019-04-28 09:55 UTC
## The expected behaviour

1. Go to someones profile.
2. Press the hamburger menu to the right and choose "Mention @`user`".
3. The reply dialog appaears.
4. Profit.

## The actual behavoir

1. Go to someones profile.
2. Press the hamburger menu to the right and choose "Mention @`user`".
3. I end up back at the user profile. 

## Workaround

I can make it work if I reload the page and then open the reply dialog.

## Information

* Pinafore 1.6.0
* qutebrowser 1.6.1
* QtWebEngine 5.12.3 (Chromium 69.0.3497.128)

It works with IceCat 60.3.0.

**Comment by nolanlawson** [comment] 2019-05-02 00:37
I can't seem to reproduce in either Chrome 74 or Firefox 66 (on Linux). I tried both pinafore.social and dev.pinafore.social.

Maybe it's a bug in Qutebrowser? Chromium 69 is a bit old (Chrome 74 is latest).

**Comment by Hund** [comment] 2019-05-02 17:51
The QtWebEngine team updated their 5.13 branch which merged the source for Chromium 73 about 4 days ago. Considering I'm only rolling with stable packages I doubt that I will see that version of QtWebEngine any time soon, unless I unmask it myself. :)

I tested with the Falcon browser (which also uses QtWebEngine) and I have the same issue there. I guess I have to wait a few month or so to see if the issue is with QtWebEngine or not. I'm not going to try any testing version considering it takes about 3 hours to compile QtWebEngine for me. :)

**Comment by nolanlawson** [comment] 2019-09-14 01:11
I'm going to close this issue since it appears to be a QtWebEngine issue, and officially Pinafore only supports the latest Chrome/Firefox/Safari/Edge. Please let me know if you have success with another browser or if your browser has updated. :)

**Closed by nolanlawson** 2019-09-14 01:11 UTC
Labels: bug
