### ISSUE TITLE
Feature Request: back button dismisses photo lightboxes instead of navigating behind them

### ISSUE THREAD

**Issue by vivlim** [nolanlawson/pinafore#397] opened 2018-06-18 18:10 UTC
Currently if I press the back button on my phone while viewing a photo, the main view behind the photo changes. This is jarring, because I expect the photo to go away when I hit back instead.

**Comment by nolanlawson** [comment] 2018-06-23 15:37
Thanks for filing! This is a duplicate of #60

**Closed by nolanlawson** 2018-06-23 15:37 UTC
