### ISSUE TITLE
Nav bar invisible when placed at bottom on Chrome on Android

### ISSUE THREAD

**Issue by nolanlawson** [nolanlawson/pinafore#2221] opened 2022-11-21 15:37 UTC
Looks like I messed something up with #2164 : https://mastodon.social/@developit/109377628451233871 

My bad for only testing in Chrome/Firefox on desktop. :stuck_out_tongue:

**Comment by bennypowers** [comment] 2022-11-21 16:08
I installed pinafor as a webapk. i did notice the pencil button floats awkwardly one header-height from the top, as well. probably related.

I couldn't reproduce this while browsing https://fosstodon.org/@pinafore/109377455374101085

**Comment by nolanlawson** [comment] 2022-11-22 01:17
I can reproduce the pencil button thing but I can't reproduce @developit's issue. I tried Chrome on Android, Safari on iOS, and Chrome emulating an Android phone via DevTools. 

Could be related to https://github.com/nolanlawson/pinafore/issues/2216 ? Extension issue?

**Comment by developit** [comment] 2022-11-22 01:40
@nolanlawson it only happens for me when using the app in a chrome tab, not when installed as a PWA in standalone mode. The bottom bar is scrolled out of view when Chrome's top bar slides down due to scrolling. https://user-images.githubusercontent.com/105127/203195995-50a70322-4796-4398-b082-30e898389e71.mp4

**Comment by nolanlawson** [comment] 2022-11-22 04:15
Weird! I can reproduce on Chrome on Android as well, but only when in non-PWA mode. Oddly it repros in Chrome, Samsung Internet, and Firefox (!).

It shows a little "preview" of the nav toolbar (i.e. like 10 pixels – you can see it in your video), but  nothing more than that. I am flabbergasted as to what is going on here.

Believe me that I don't have any logic that is trying to detect the scroll position or something and hide the nav bar. This might require some serious debugging to figure out why this is happening…

**Comment by leettaylor** [comment] 2022-11-22 08:07
[This line is the issue:](https://github.com/nolanlawson/pinafore/blob/6b1533c9476de9f098c2c66c2a7a0f5acdf36b00/src/build/template.html#L37)

```scss
--nav-top: calc(100vh - var(--nav-total-height));
```

In Chrome mobile `100vh` doesn't take into account the full address bar

> Lengths defined in viewport units (i.e. vh) will not resize in response to the URL bar being shown or hidden. Instead, vh units will be sized to the viewport height as if the URL bar is always hidden. That is, vh units will be sized to the "largest possible viewport". This means 100vh will be larger than the visible height when the URL bar is shown. ([Source](https://developer.chrome.com/blog/url-bar-resizing/))

Not sure what the current hack is to work around it but [this article](https://css-tricks.com/the-large-small-and-dynamic-viewports/) has links to a few hacks and also discusses the way it will be resolved in the spec eventually with `dvh`.

**Closed** 2022-11-24 23:24 UTC
Labels: bug
