### ISSUE TITLE
Retweet button is smaller than others - `fa-retweet` is not a square

### ISSUE THREAD

**Issue by xnuk** [nolanlawson/pinafore#2293] opened 2022-12-04 13:59 UTC
![](https://user-images.githubusercontent.com/3071003/205494397-e47570c9-4b52-4188-b3b1-3143b54d22bd.png)

Size of the retweet button is 2048x1792:

https://github.com/nolanlawson/pinafore/blob/380d2a0d451cd6d74483a44fb5ef5f4a263c728b/src/thirdparty/font-awesome-svg-png/white/svg/retweet.svg#L1

While sizes of all `IconButton`s are 24x24px (or smaller square sizes):

https://github.com/nolanlawson/pinafore/blob/380d2a0d451cd6d74483a44fb5ef5f4a263c728b/src/routes/_components/IconButton.html#L31-L36

That makes bit smaller than other icons.

**Comment by nolanlawson** [comment] 2022-12-04 19:26
thanks for opening the issue! This looks like a duplicate of #916.

Currently I would prefer not to do hacks just for a particular icon; I would rather fix the source svg.

**Closed by nolanlawson** 2022-12-04 19:26 UTC
