### ISSUE TITLE
Follow requests are just the person's name

### ISSUE THREAD

**Issue by graue** [nolanlawson/pinafore#2263] opened 2022-11-27 08:15 UTC
Hi, when someone requests to follow me, the notification I see in Pinafore is just the person's name. It doesn't say "...requested to follow you" or anything. It doesn't have a way to accept or reject, it only links to their profile.

In this screenshot, the notifications that are just a profile pic and name are follow requests:

![pina](https://user-images.githubusercontent.com/1730853/204125446-5645d4d4-96ad-4a50-b278-59f909d9aebd.png)

This is on a server running Mastodon 4.0.2. I saw an issue, #1800, that sounded related to this, but it appears to be somewhat different.

**Comment by nolanlawson** [comment] 2022-11-27 15:45
Yeah looks like follow request notifications are a new thing. This used to work differently in Mastodon – there was a separate endpoint for follow requests.

**Comment by graue** [comment] 2022-12-05 09:30
Took a look at implementing this, and I have this so far:

![request](https://user-images.githubusercontent.com/1730853/205600205-25d453c6-a220-4da4-bf41-c28798448c67.png)

Now it needs a way to accept or reject the request.

I could copy Mastodon's design of inline Accept and Reject buttons, but I generally like to view the requester's profile first, so the flow I'd really like to see here is:
1. The whole notification is clickable and goes to their profile
2. On their profile, I can see that they've requested to follow, and accept or reject there

Do you think that makes sense?

Also, I was thinking of compositing the existing user.svg and hourglass.svg to make a new icon of a user with a little hourglass in the corner. That seems clearer than just the hourglass in this context, but let me know if you disagree.

**Comment by nolanlawson** [comment] 2022-12-05 15:55
@graue Looks nice! If you'd like to create a new icon, please feel free to go ahead and add it to `src/thirdparty/font-awesome-svg-png/`. Although just glancing at it, I wonder if the "icon within an icon" would be too small to distinguish at that size, so I'd be fine with just the hourglass.

I was originally thinking that the follow request notification, when clicked, could go to `/requests` (i.e. the list of follow requests). Sure it's the full list of follow requests, but I figure most people won't have a lot at any one time. Plus it's easy to implement.

Going to the profile page is fine too, but they might be confused about how to accept the follow request. I don't think there's currently a way to do this from the profile page.

**Comment by nolanlawson** [comment] 2022-12-11 19:50
It looks like this is actually a duplicate of #1800

**Closed by nolanlawson** 2022-12-11 19:50 UTC
Labels: bug
