### ISSUE TITLE
I cannot add instance, the button is just greyed out?

### ISSUE THREAD

**Issue by Hund** [nolanlawson/pinafore#363] opened 2018-06-02 16:48 UTC
I cannot add instance, the button is just greyed out? I'm using qutebrowser 1.3.1 with QtWebKit (WebKit 602.1).

**Comment by Hund** [comment] 2018-06-02 16:49
Here's a picture of it: https://framapic.org/TSacMIM3c6tC/H8Bze9Et9l5p.png

**Comment by nolanlawson** [comment] 2018-06-04 16:18
Can you paste your user agent string? Pinafore supports the latest versions of Edge/Firefox/Safari/Chrome. Have you tried in one of those browsers? I'm not sure how recent WebKit 602.1 is (e.g. what it corresponds to in terms of Safari versions).

Is there an error in the console?

**Comment by Hund** [comment] 2018-06-18 08:21
Ops, I missed your reply. :) No, I don't use any of them.

`Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/602.1 (KHTML, like Gecko) qutebrowser/1.3.2 Version/9.0 Safari/602.1`

This line:

```
<!-- insert inline script here --><script>(function () {'use strict'; // For perf reasons, this script is run inline to quickly set certain styles.
```

Created this error:

> Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'sha256-0MCgHAFNUG4VRZg8Hh2LgrBtmMzg4KnM+3wJ/vRlpV8='".

It's from this part:

```html
  <!-- auto-generated w/ build-inline-script.js -->
  <!-- insert inline script here --><script>(function () {'use strict'; // For perf reasons, this script is run inline to quickly set certain styles.
// To allow CSP to work correctly, we also calculate a sha256 hash during
// the build process and write it to inline-script-checksum.json.
window.__themeColors = {
  'default': 'royalblue',
  scarlet: '#e04e41',
  seafoam: '#177380',
  hotpants: 'hotpink',
  oaken: 'saddlebrown',
  majesty: 'blueviolet',
  gecko: '#4ab92f',
  ozark: '#5263af',
  cobalt: '#08439b',
  sorcery: '#ae91e8',
  offline: '#999999'
}
```

**Comment by nolanlawson** [comment] 2018-06-23 15:36
Hmm OK so there are two bugs here, but AFAICT they both stem from using an older version of WebKit. The latest Safari 11 has AppleWebKit/605.1.15 in the user agent whereas Qutebrowser has 602.1. At least, that's my hunch, since I can't seem to reproduce in Safari 11.

**Comment by Hund** [comment] 2018-06-23 17:35
I'm using the latest available version of QtWebKit, witch is currently [5.212.0 Alpha](https://github.com/annulen/webkit/releases/tag/qtwebkit-5.212.0-alpha).

**Comment by migurski** [comment] 2018-08-19 01:59
I see this issue also, in Safari Version 10.1.2 (12603.3.8).

**Comment by nolanlawson** [comment] 2018-08-27 01:57
AFAICT this problem does not occur in Safari 11.

As for QtWebKit, right now my policy is "latest version of Chrome/Edge/Firefox/Safari" since those are the main independent browser implementations. So for any browser downstream from them, I prefer to just wait for them to update to the latest, unless it's a really popular browser and the fix is easy. In this case the fix is difficult and would require potentially weakening security by weakening CSP.

Closing this issue, hoping QtWebKit updates soon!

**Closed by nolanlawson** 2018-08-27 01:57 UTC
Labels: bug
