### ISSUE TITLE
fallback to non-native emoji if native picker fails

### ISSUE THREAD

**Issue by Oreolek** [nolanlawson/pinafore#1869] opened 2020-09-10 11:46 UTC
It just says `Your browser does not support color emoji.` and i can't select anything.

**Comment by nolanlawson** [comment] 2020-09-10 23:56
Thanks yup, this is caused by https://github.com/nolanlawson/emoji-picker-element/issues/34

Out of curiosity, what kind of device/browser are you using? It'd be good to know whether we can even fall back to some minimal level of support (e.g. black-and-white basic emoji).

**Comment by Oreolek** [comment] 2020-09-11 19:56
Just plain desktop Linux firefox. I do have `fonts-noto-color-emoji` installed.

**Comment by nolanlawson** [comment] 2020-09-13 17:11
@Oreolek Which version of Firefox, which Linux distro? Firefox comes with its own emoji (Twemoji) installed, so it should work out-of-the-box. I'm personally using Ubuntu 20.04 with Firefox 80.0.1.

**Comment by nolanlawson** [comment] 2020-09-13 17:12
Also I'm not using PNGs or SVG fonts; `emoji-picker-element` just includes the native emoji inline as-is. You can test native emoji by going to a site like https://emojipedia.org/ and seeing if any empty boxes are rendered.

**Comment by Oreolek** [comment] 2020-09-13 18:20
Ubuntu 20.04, Firefox 80.0.1 and emojipedia has all their color emoji.

**Comment by nolanlawson** [comment] 2020-09-13 19:19
@Oreolek Have you disabled canvas or changed other fingerprinting/privacy settings in Firefox? `emoji-picker-element` uses canvas to figure out if color emojis are supported or not.

**Comment by Oreolek** [comment] 2020-09-14 10:14
`resistFingerprinting` is set to `true` but canvas is enabled for pinafore.

**Comment by nolanlawson** [comment] 2020-09-20 21:45
Ahhh, thanks for looking into this. So I guess this is just a Firefox issue? If so, I'll close this issue, thanks for letting me know!

**Closed by nolanlawson** 2020-09-20 21:45 UTC
Labels: bug

**Comment by Oreolek** [comment] 2020-10-30 12:28
Firefox 82 landed, so the picker works now.

**Comment by nolanlawson** [comment] 2020-11-14 19:44
Nice! Glad to hear :)
