### ISSUE TITLE
Allow Browsing Instance Timelines (Local, Federated) Without Logging In

### ISSUE THREAD

**Issue by jet082** [nolanlawson/pinafore#2264] opened 2022-11-27 14:56 UTC
One of the 'killer features' for me of apps like Toot! and Fedilab is the ability to browse the local and federated timelines of other instances without needing to log into them. This is great for finding new people to follow.

It would be amazing to see this functionality on pinafore. Perhaps when adding an instance, the option could exist for 'Add Without Logging In" - and then you would follow or reply or whatever based upon the active account chosen in the "Account Switcher" noted in #11.

**Comment by nolanlawson** [comment] 2022-11-27 15:46
Thanks for opening! This looks like a duplicate of #1929. Closing for now.

**Closed by nolanlawson** 2022-11-27 15:46 UTC
