### ISSUE TITLE
"No video with supported format and MIME type found." on videos native interface can play

### ISSUE THREAD

**Issue by Archenoth** [nolanlawson/pinafore#1590] opened 2019-10-16 22:31 UTC
The video embedded in this post [here](https://awoo.space/@thingywott/102974088447947047) seems to play perfectly on awoo.space, but I see the following when I attempt to play it in Pinafore:
![No video with supported format and MIME type found.](https://user-images.githubusercontent.com/1385527/66963466-fde12d00-f030-11e9-9710-6f0d463c5b86.png)

The following are the headers that Pinafore sends and receives for this video:
![Request headers for Pinafore's inerface](https://user-images.githubusercontent.com/1385527/66963608-51ec1180-f031-11e9-8368-f25a6a15750a.png)

For comparison, awoo.space's main interface has these:
![Request headers for awoo.space's interface](https://user-images.githubusercontent.com/1385527/66963678-7f38bf80-f031-11e9-92fd-1ea75401a2e3.png)

It also seems to chunk the video:
![A list of requests for the same video, chunked across these requests. They all return 206 except the last one which has no response](https://user-images.githubusercontent.com/1385527/66963704-924b8f80-f031-11e9-8d91-52e4f513618b.png)

(Also, the last request never seems to get a response?? Firefox doesn't show me the headers it sends either)

Any idea what's going on here?

This is on Firefox 69.0.2 (64-bit) on Windows 10 Pro. (10.0.18362 Build 18362)

**Comment by nolanlawson** [comment] 2019-10-17 01:02
Thanks for the bug report. I cannot reproduce in Firefox 69.0.3 on either Windows 10, Ubuntu Linux, or Android. My Windows version is 1809 (17763).

Note that I am reproducing via toot.cafe, by pasting the URL to the toot into the search bar (because I don't have an awoo.space account).

So the problem could possibly be:

- awoo.space's media host (compared to toot.cafe's media host)
- my Windows version (17763 vs 18362)
- something else

My hunch is that it has something to do with the range headers or the `type=*` on the `<video>` tag which were added to fix Safari bugs. (#1537 #1555).

By any chance, could you try in another browser? Or try using another instance which is connected to `awoo.space`, rather than `awoo.space` itself? That may help narrow down the cause of this bug.

**Comment by nolanlawson** [comment] 2019-10-17 01:03
I do notice that in your screenshot, a 200 is returned by Pinafore rather than a 206 by awoo.space. So it could indeed be #1555 that is the cause.

**Comment by nolanlawson** [comment] 2019-10-17 01:08
Bizarre, I tried directly injecting the `media.awoo.space` URL into Pinafore's `<video>` tag, but I still cannot reproduce, even in Firefox on Windows.

Can you check that your Pinafore version is v1.15.0? It's at https://pinafore.social/settings/about. Could you also check that you haven't disabled Service Workers in Firefox? If the Service Worker is active, then the response should be 206 rather than 200.

**Comment by Archenoth** [comment] 2019-10-17 06:13
I can confirm it's v1.15.0.

I also just replicated it on a separate Windows 10 Home laptop (Also 10.0.18362 Build 18362 though) with Firefox 69.0.3 (64-bit), and then again in Edge 44.18362.387.0

![Edge refusing to play the same video as before](https://user-images.githubusercontent.com/1385527/66981845-30f7e080-f072-11e9-8c0d-602d617c17fe.png)

However! It looks like the video played when I logged into Pinafore with my mastodon.social account. Maybe glitchsoc is doing something different than what's upstream and that's causing breakage?

**Comment by nolanlawson** [comment] 2019-10-17 14:12
Can you try at https://pinafore-1i23wzm4v.now.sh and see if that fixes it? I haven't been able to reproduce locally yet.

**Comment by nolanlawson** [comment] 2019-10-18 01:34
It seems like it may be an issue with awoo.space's media host (Wasabi) rather than glitch-soc. I suspect that a plain `<video>` tag pointing to that URL would exhibit the same problem.

As a test, could you try visiting http://bl.ocks.org/nolanlawson/raw/e64ca39ef3dade59cc4f6e250bfbcad7/ and see if it can play either video for you? Those are basically just the `<video>` tags exactly as Pinafore would display them. If it doesn't work but it works from `awoo.space`, then there's something different in the `<video>` tag attributes or maybe in the way Wasabi is serving it cross-origin.

**Comment by nolanlawson** [comment] 2019-10-18 01:38
(For the record, on my version of Windows, both of the `<video>` tags on that page work for me in both Firefox and Edge.)

**Comment by Archenoth** [comment] 2019-10-18 02:24
Oh, this is fun! Both seem to work for me on your test page.

When I first open the page, all the chunks download, and when I play either of them, I get those responseless requests in my log too (The last two):
![Firefox network log for showing the chunks of both videos](https://user-images.githubusercontent.com/1385527/67060834-a8ce1580-f11b-11e9-8963-63441e916589.png)

Here's what one of the chunk requests looks like:
![The request and response headers for one of the chunked uploads](https://user-images.githubusercontent.com/1385527/67060890-d7e48700-f11b-11e9-9104-3a6229d32e54.png)

**Comment by nolanlawson** [comment] 2019-10-18 13:50
OK in that case, this must be a Service Worker issue, possibly caused by #1555. I can tell because in your screenshots the response is 200 when it fails and 206 when it succeeds. Also that sample page doesn't have a Service Worker, whereas Pinafore does.

What's odd is that I still can't repro the failure, but I suspect it has something to do with the Service Worker returning 200 instead of 206 for the range requests.

**Comment by nolanlawson** [comment] 2019-10-18 13:59
Actually now that I look at your screenshots again, it appears that Pinafore is just not doing range requests at all. I don't see any `Range` or `Content-Range` headers anywhere. Very strange...

Out of curiosity, you haven't been able to repro this on any non-Windows machine? And you've only repro'd it on awoo.space?

**Comment by nolanlawson** [comment] 2019-10-18 14:09
I think what may be going on here is that our Service Worker fix is stripping the headers when it sends the range request, which for some reason is causing bugs in Edge and Firefox. This "fix" is only needed for Safari, so perhaps we should just disable it for non-Safari browsers.

**Comment by aadilayub** [comment] 2019-10-18 14:09
![Screenshot from 2019-10-18 19-07-28](https://user-images.githubusercontent.com/31581044/67101226-b0a0bf00-f1da-11e9-88d3-2ed85232aea3.png)

Confirming from merveilles.town
Browser: Firefox 69.0.3
OS: Fedora 30

**Comment by nolanlawson** [comment] 2019-10-18 14:23
@aadilayub That's really interesting, so far we've only seen this on Windows. Another data point! :)

Could somebody test this out at https://pinafore-fwh2osyys.now.sh and see if it's fixed? I am still not able to reproduce on any of my own machines.

**Comment by nolanlawson** [comment] 2019-10-18 14:29
merveilles.town seems to be using Amazon for media hosting, not Wasabi. Interesting...

**Comment by Archenoth** [comment] 2019-10-18 14:38
Ooh! That looks like it fixes it!

(In the meantime, I can also confirm that ontop of Linux, this also happens on Android--lemme see if your link fixes it on those too)

**Comment by Archenoth** [comment] 2019-10-18 14:50
Update: It seems they do!

Looks like your fix works in both Firefox on Linux Mint and in a Chrome PWA on Android. (Both which I verified weren't working before testing the new version)

**Comment by nolanlawson** [comment] 2019-10-18 14:57
Thanks for the feedback. The fix is in https://github.com/nolanlawson/pinafore/pull/1594 and I'll test a bit more before deploying.

I think this is probably not a browser or OS issue but rather than issue with the media server. Probably the reason I am having so much trouble reproducing is because I'm not on awoo.space or merveilles.town or any other instance that is exhibiting these issues.

**Comment by Archenoth** [comment] 2019-10-18 15:02
Hee, anytime..! ^^

I figured it probably wasn't browser-specific, which is why I lazed out when it came to version numbers last post.

But also, for reals, thank you for the fix! I really appreciate all the effort you put into Pinafore~

**Comment by nolanlawson** [comment] 2019-10-19 01:55
Confirmed that I can reproduce in Chrome on Ubuntu by using awoo.space's media server. The error is a CORS error, because awoo.space's media host doesn't have CORS enabled.

Note that I don't think it's the responsibility of every media host to enable CORS (although it helps, e.g. with things like OCR on images too), but rather it's Pinafore's responsibility to gracefully handle any kind of media server. :)

**Comment by nolanlawson** [comment] 2019-10-19 02:03
Thanks for all your help @Archenoth !

**Closed** 2019-10-19 02:03 UTC
Labels: bug

**Comment by Archenoth** [comment] 2019-10-19 02:41
Happy I could help~ ^^
