### ISSUE TITLE
Add word filters to hide statuses containing certain words

### ISSUE THREAD

**Issue by GoodInDeed** [nolanlawson/pinafore#1050] opened 2019-02-25 20:29 UTC
My group is working on a course project, and I have noticed that there are some complain about mastodon that some users is not interested in some topic/aspect and there is nothing they can do with this. So we setup a localhost and now we are trying to develop a word detect function on current Pinafore, and I hope to create a new tab on the top-bar for detail of word detect function. If you have any advise for this please let me know. Thanks for you help in advance.

**Comment by nolanlawson** [comment] 2019-02-25 22:32
I thought Mastodon may already have some kind of system for filtering toots by a list of words or a regular expression, but I can't seem to find this feature anymore. If it does exist, I'm not sure if it works client-side or server-side. If it exists server-side then it should be fairly easy to implement; if it exists client-side then it would be much more work.

I was thinking that, if we were to implement it in Pinafore client-side, perhaps the right spot would be in the settings. For instance, you could list some words that you never want to see in your timeline or notifications in the settings, and then it would be ignored.

Unfortunately this feature would probably be complicated to implement, as it relies on implementing a generic filter system (which is already covered in another issue: https://github.com/nolanlawson/pinafore/issues/369). When that filtering system is in place, this should be much easier to implement.

**Comment by nolanlawson** [comment] 2019-03-03 21:01
Actually it just occurred to me that this will be even trickier than basic client-side filters (#369), because this assumes we are holding onto the entire status content, whereas the client-side filters assumes we're only holding on to some small metadata (reply to ID, reblog ID, etc.). Unless I keep the full status content in memory at all times, I'm not sure how I would implement this client-side.

**Comment by nolanlawson** [comment] 2019-03-31 22:56
Closing as duplicate of #369

**Closed by nolanlawson** 2019-03-31 22:56 UTC
Labels: enhancement
