### ISSUE TITLE
No ability to refresh if drag to refresh is disabled

### ISSUE THREAD

**Issue by Cellivar** [nolanlawson/pinafore#620] opened 2018-11-06 06:27 UTC
I have Pinafore installed to my home screen on my Note 9 on Android 8. I regularly make use of a device called a Lap Dock that effectively turns my phone into a laptop with a trackpad instead of a touchscreen. As a result of this input experience I disabled drag to refresh, to prevent very common accidental page refreshes when scrolling. 

This prevents my ability to refresh for updates when using the PWA view through the Chrome add to home screen mechanism. I have also had instances where I received a push notification but did not see the notification in my notifications view. I was unable to refresh, requiring closing the app via the app switcher. 

Would it be possible to implement an alternative refresh operation, such as a fast double-tap on the tab icon or other mechanism?

**Comment by nolanlawson** [comment] 2018-11-21 08:21
I think this bug is a duplicate of #390. I definitely agree that the current streaming system is unreliable, and it'd be nice to either 1) fix it, or 2) have an explicit refresh button.

**Closed by nolanlawson** 2018-11-21 08:21 UTC
Labels: bug
