### ISSUE TITLE
Offline UI improvements

### ISSUE THREAD

**Issue by Radtoo** [nolanlawson/pinafore#1926] opened 2021-01-31 16:16 UTC
It would be nice if media/posts deleted on remote servers were still displayed in pinafore's view, but grayed out / displayed in a colored background / indicated with some icon.

It would be nice if it was more clearly visible which attached media are not yet stored offline in full (because they failed and/or didn't get saved yet).

**Comment by nolanlawson** [comment] 2021-03-14 03:14
Thanks for opening the issue! I'll close it as a duplicate of https://github.com/nolanlawson/pinafore/issues/531

I think in particular the grayed-out view for deletions is reasonable... probably more likely this wouldn't show the original content, but would instead show something better than the current 404 page. Reason being, if someone deleted their toot, then there's probably a good reason for it, and it would be a bit presumptuous of Pinafore to continue showing the toot even if someone deleted it. (E.g. maybe they were embarrassed about what they said.)

**Closed by nolanlawson** 2021-03-14 03:14 UTC
Labels: enhancement

**Comment by Radtoo** [comment] 2021-03-27 20:47
1. I think deleting a saved toot is a bad idea unless you can reliably distinguish between an user deleting it themselves vs. a server having a technical issue getting reset for technical reasons. Or the server intentionally purging some unpleasant information. A third party unintentionally or intentionally deleting information is not really legitimate.

2. If it's ever a matter of history/proof of who said what, should only users prepared to record screenshots (or using clients that record) have records but pinafore users not have the context? A lot of people routinely screenshot or text share or whatever else they intend to use as funny or attack later and you really can't stop them, but few record context over which they possibly could be attacked out of context.

I only see logs as beneficial. The vast majority of deletions will completely remain nonpublic with the people who originallz saw them. And in the few instances where it matters, logs are best if available.
