### ISSUE TITLE
Toot contents isn't included in arrow key navigation.

### ISSUE THREAD

**Issue by rkingett** [nolanlawson/pinafore#1737] opened 2020-04-05 17:27 UTC
Running the latest version of NVDA and FireFox, the toot contents are not heard when arrowing up and down, left and right.

To reproduce.

Run NVDA,

Enter forms mode/focus mode.

tab until you get to the timeline.

Press up, down, left, or right.

Expected behavior.

When pressing up and down, the full contents of the toot will be read including links, after the display name.

When pressing left and right, the toot contents would be read after pressing left and right.

Actual behavior.

When pressing up or down,

Item number, display name, then it is silence after reading the display name.

When pressing left or right.

Everything else is announced except for the Toot contents. Links and hashtags in toots are read when pressing left and right.

**Comment by nolanlawson** [comment] 2020-04-25 21:11
Thanks for filing the bug. I'm guessing it may be related to #1736 since these both seem to involve forms mode (and I hadn't previously tested forms mode).

When pressing left or right, does it change columns? I.e. change from the Home timeline to the Notifications timeline? This is a built-in keyboard shortcut.

**Comment by rkingett** [comment] 2020-04-25 21:42
It seems to not work for me, the built in keyboard shortcut. Mastodon.social got this working, so perhaps it may be worth looking at what they did?

On the main website, I enable forms mode after navigating to the timeline. I press up and down arrow keys. Everything is read. Same for when I press left and right arrow keys. On Mastodon.social.

**Comment by nolanlawson** [comment] 2020-04-25 22:09
Which browser are you using? Have you disabled the left/right keys in the hotkey settings?

**Comment by rkingett** [comment] 2020-04-25 22:18
I checked in the preferences, and it says that   Left/right arrow keys change focus rather than columns/media is checked.

It actually does change to notifications, right arrow key, when I move away from the timeline completely. If I first hit up or down, and then right arrow key, it cycles through every element except the actual text of the toot.

**Comment by nolanlawson** [comment] 2020-04-25 22:35
Ahhhh okay, I understand now. Yes, the left/right feature in this case is designed to mimic Tab/Shift-Tab, so it's only supposed to cycle through focusable elements on the page (i.e. not the toot text, but rather things like links and buttons). This is designed for clients like KaiOS where there is no Tab Key but only a d-pad.

So to me, it appears that the left/right keys are working as designed. As for the up/down keys, they are supposed to cycle through the statuses, not all focusable items.

I am testing right now in NVDA and Firefox 75, and I didn't enable forms mode, but I can confirm that NVDA overrides all four of the left/right/up/down keys. The effect is that none of them work the way I intend them to. When I close NVDA they work fine.

I'll keep testing this, but I assume there is some NVDA setting or mode where it will delegate up/down/left/right to the web page rather than try to do its own behavior.

**Comment by nolanlawson** [comment] 2020-04-25 22:37
@marcozehe I believe you had a recommended set of settings for NVDA so that it would work well with web pages that implement the WAI-ARIA "feed" model, such as Pinafore? By any chance could you share how you're doing this?

**Comment by nolanlawson** [comment] 2020-04-25 22:44
OK apparently if I add `role="application"` to the entire `<body>`, then the keyboard shortcuts work correctly, and NVDA does not try to override them ([source](https://stackoverflow.com/a/41523306)). I'll explore this option, but I'm a bit nervous about playing around with ARIA roles, so I'll have to do some research first.

**Comment by MarcoZehe** [comment] 2020-04-25 23:01
No need for role „application“. NVDA+Space to turn on forms mode, then up and down through statuses works for me. Don‘t even need to tab to main timeline first. BTW, the shortened label setting is off, it is no longer needed, IMO. Only setting I changed was to suppress emojis in names.

**Comment by nolanlawson** [comment] 2020-04-25 23:25
Thanks, Marco! I can confirm that by pressing CapsLock+Space to enter forms mode, the up and down keys cycle through the statuses and read out the long labels. Pressing left and right cycles between columns (e.g. Home/Notifications). It looks like `role=application` functions basically the same as "forms mode."

For the record, I am also not able to reproduce #1736 - when autocomplete results are available, pressing left and right moves the cursor left and right, whereas pressing up and down cycles through the autocomplete results correctly.

@rkingett Maybe the main issue is the "left/right keys change focus" setting?

**Comment by nolanlawson** [comment] 2020-04-25 23:26
I'm using NVDA 2019.3.1 and Firefox 75.0 on Windows 10 BTW.

**Comment by rkingett** [comment] 2020-04-25 23:29
After changing a few settings, it now works for me.

the shortened Aria label setting is off. It was previously on.

The disable tappable area in statuses was checked. I unchecked it.

Now it works fine for me. The Toot content now reads without me having to do anything extra.

**Comment by nolanlawson** [comment] 2020-04-26 20:01
Awesome, glad to hear it! :) Closing this issue for now.

**Closed by nolanlawson** 2020-04-26 20:01 UTC
Labels: accessibility, bug
