### ISSUE TITLE
"Error: undefined" when adding an instance

### ISSUE THREAD

**Issue by timmc** [nolanlawson/pinafore#37] opened 2018-04-09 17:43 UTC
When attempting to add an instance, `https://i.write.codethat.sucks`, I get: `Error: undefined. Is this a valid Mastodon instance?` I see an OPTIONS, a GET, and a POST, all succeeding. In the console, an `InvalidStateError` and then some error event involving the string `IDBOpenDBRequest`. Something to do with IndexedDB?

Firefox ESR 52, Debian Linux 9.

**Comment by nolanlawson** [comment] 2018-04-09 17:53
Do you get this error the moment you click "add instance"? If so, I think it may be related to https://github.com/nolanlawson/pinafore/issues/31

The temporary fix is to clear out the cache/stored data for pinafore.social and try again. I think maybe the trailing slash bug might put your IDB/LocalStorage in a weird state.

**Comment by timmc** [comment] 2018-04-09 22:25
No, there's a brief delay. Nothing in IDB according to devtools, and error still present after clearing LocalStorage. I don't know how to get a timestamp for the error so as to match it up to network call timings...

**Comment by nolanlawson** [comment] 2018-04-10 02:57
On second glance, I think the issue may be Firefox 52. I only tested the latest versions of Firefox (v58+ IIRC). So it may be that it's just broken in v52. In any case, I can't reproduce when I type `https://i.write.codethat.sucks` into the instance input and press the "add instance" button. :confused:

**Comment by skiant** [comment] 2018-04-23 22:17
I get the same issue on Firefox 59, Windows 10.
Sourcemaps being present, I digged into it and it seems that the function `getOrCreateInstanceCache` in `_database/cache.js` is never called for some reason?

**Comment by rubahness** [comment] 2018-06-22 01:38
I get this error and am also using FF52 ERS :|

**Comment by nolanlawson** [comment] 2018-12-06 06:16
This should be fixed by #733 where we detect broken IndexedDB and show a warning

**Closed by nolanlawson** 2018-12-06 06:16 UTC
Labels: bug
