### ISSUE TITLE
mp4s don't play in Safari

### ISSUE THREAD

**Issue by feld** [nolanlawson/pinafore#1547] opened 2019-09-27 21:54 UTC
![CC1C7267-1593-4900-BBD9-D4DEA57B9768](https://user-images.githubusercontent.com/40271278/65804352-a0ec0880-e14f-11e9-9f3a-1ac9ff74cfd5.png)

I'm away from a real keyboard and can't debug further right now but this behavior is exhibited by Safari if the media is being served from a web server that doesn't support Range Requests. I didn't think Pinafore proxied any content itself, so perhaps there is another explanation.

**Comment by nolanlawson** [comment] 2019-10-01 10:22
This should be fixed in https://dev.pinafore.social . I made a fix recently for this.

**Comment by feld** [comment] 2019-10-01 17:51
Issue is persisting for me on dev.pinafore.social

**Comment by nolanlawson** [comment] 2019-10-07 09:59
iOS 13?

**Comment by sgenoud** [comment] 2019-10-07 10:07
I can reproduce this both on iOS 13 and 12.

**Comment by nolanlawson** [comment] 2019-10-07 11:48
Hmm so https://github.com/nolanlawson/pinafore/pull/1537 was supposed to fix this, but apparently it didn't. I don't have a great setup for testing iOS devices anymore (because I'm on Linux), so this is really difficult for me to fix. The bug appears to be iOS-only.

**Comment by sgenoud** [comment] 2019-10-07 11:50
> The bug appears to be iOS-only.

![Capture d’écran 2019-10-07 à 13 49 39](https://user-images.githubusercontent.com/263325/66309236-65003280-e909-11e9-8af5-e1c61d6b814f.png)

It is also reproduceable on Safari desktop.

**Closed** 2019-10-07 15:36 UTC
Labels: bug
