### ISSUE TITLE
Allow logged out user to view content from a default instance

### ISSUE THREAD

**Issue by uiri** [nolanlawson/pinafore#869] opened 2019-01-08 06:15 UTC
I suppose this is related to #35 -- I'm not concerned about the login flow, but right now there is no obvious way to use Pinafore as an alternative frontend and still allow for canonical links to an instance's toots and user profiles.

There are definitely APIs for this since both Mastodon's frontend and Pleroma's frontend allow for this but I suspect that they differ between Mastodon and Pleroma...

**Comment by nolanlawson** [comment] 2019-01-12 17:37
Yeah I think this is a duplicate of #35. Although ideally if Pinafore was hosted at e.g. `pinafore.myinstance.com` then users would be automatically logged in if they have the cookie from `myinstance.com`.

**Closed by nolanlawson** 2019-01-12 17:37 UTC

**Comment by uiri** [comment] 2019-01-12 19:02
Can you clarify how this is a *duplicate* of #35?
