### ISSUE TITLE
Docker image build fails

### ISSUE THREAD

**Issue by pwFoo** [nolanlawson/pinafore#2036] opened 2021-05-02 08:07 UTC
Hi,
any idea why the latest versions fail with docker image build?
```
asset service-worker.js 12.9 KiB [emitted] [minimized] (name: service-worker) 1 related asset
orphan modules 17.8 KiB [orphan] 8 modules
./src/service-worker.js + 6 modules 24.2 KiB [built] [code generated]
webpack 5.23.0 compiled successfully in 5387 ms

> Built in 4m17s
> Crawling http://localhost:22939/
> timed out waiting for connection
error Command failed with exit code 1.
```

Still running 1.20.0 because newer versions fail to build because of http timeout to http://localhost:22939 from inside of my docker build process? :(

**Comment by nolanlawson** [comment] 2021-05-02 15:01
What environment is this? What OS, what Node version, what hardware?

I know folks have had trouble building Pinafore on Raspberry Pis; you might need to build on one machine and then transfer the files to another machine.

**Comment by pwFoo** [comment] 2021-05-02 15:05
Running on a x86_64 vmware guest, linux / RancherOS. No rasp. Build in docker with your dockerfile.
Older versions I just created an image with docker build and than run from that image. Now I can't run newer versions, because docker image build fails.

**Comment by pwFoo** [comment] 2021-05-22 21:34
Problem still persists with v1.24.4

**Comment by vrutkovs** [comment] 2021-05-29 08:42
This seems to be intermittently failing in docker: I've hit this on my first build, but then it passed on another build:
```
> Built in 2m22s
[36m[1m> Crawling http://localhost:22939/[22m[39m
listening on port 22939
[90m[1m   24.2 kB[22m[39m   local/index.html
[90m[1m     28 kB[22m[39m   settings/index.html
[90m[1m   27.3 kB[22m[39m   settings/instances/add/index.html
[90m[1m   26.3 kB[22m[39m   settings/about/index.html
[90m[1m   25.9 kB[22m[39m   index.html
[90m[1m   24.3 kB[22m[39m   notifications/mentions/index.html
[90m[1m   24.3 kB[22m[39m   notifications/index.html
[90m[1m   25.2 kB[22m[39m   requests/index.html
[90m[1m   25.2 kB[22m[39m   muted/index.html
[90m[1m   25.2 kB[22m[39m   blocked/index.html
[90m[1m   25.4 kB[22m[39m   pinned/index.html
[90m[1m   24.5 kB[22m[39m   community/index.html
[90m[1m   24.2 kB[22m[39m   federated/index.html
[90m[1m   24.2 kB[22m[39m   favorites/index.html
[90m[1m   24.2 kB[22m[39m   direct/index.html
[90m[1m   24.2 kB[22m[39m   bookmarks/index.html
[90m[1m   24.5 kB[22m[39m   search/index.html
[90m[1m   28.5 kB[22m[39m   settings/general/index.html
[90m[1m     26 kB[22m[39m   settings/instances/index.html
[90m[1m   27.6 kB[22m[39m   settings/wellness/index.html
[90m[1m   28.4 kB[22m[39m   settings/hotkeys/index.html
[90m[1m   23.7 kB[22m[39m   service-worker-index.html
```

**Comment by DavidBruant** [comment] 2021-06-27 14:54
I have the same problem

I'm on:
- hardware is my laptop (common HP Pro, x86_64, nothing special i think)
- Ubuntu 20.04
- Node v14.17.1

I just did a fresh install of docker and docker-compose, so i don't think this is it

My machine is ~8yo and is fairly slow which might explain why i get the timeout reliably

I don't understand what the "crawling" step is about and i'm happy to investigate with a little guidance about what it's meant to do (is it like crawling for the purpose of generating the static html files ?) and which dependency triggers it

**Comment by nolanlawson** [comment] 2021-06-28 14:12
I think this is the same issue as #1924 so I'm going to close it as a duplicate.

As far as I can tell, the issue is that lower-powered machines run into timeouts when crawling the Sapper server during the export process. Unfortunately this is just how `sapper export` works, at least in the fork of Sapper which I'm using. And sadly not only am I using an older Sapper fork in order to work around various issues, but Sapper itself has been deprecated in favor of SvelteKit.

Off the top of my head, we could try increasing the timeout (this has not worked historically though), or we could try staggering the HTTP requests so they don't happen all at once. In the meantime, the workaround is to build Pinafore on a powerful enough machine.

**Closed by nolanlawson** 2021-06-28 14:12 UTC
Labels: bug
